 let list = [
    //***********************producto******************
    {producto: 'SOURDOUGHT', ingrediente: '400gr de harina" - 230 gr de agua" - 10 de sal" - 160 de masa madre" '}, 
    {producto: 'PIZZA', ingrediente: '5gr levadura" - 400gr de harina" - 200ml de agua" - 2 cucharadas de aceite de oliva" - 1 pizca de sal" - Masa madre" '},
    {producto: 'FOCACCIA', ingrediente: '500 gr de harina" - 15 g de levadura" - Agua tibia" - 10 gr de sal"- 45 ml de aceite de oliva"- 100 gr de queso parmesano" - 5 gr de romero" '},
    {producto: 'CIAPATTA', ingrediente: '500 gr de harina" - 15 g de levadura" - Agua tibia" - 10 gr de sal" - 45 ml de aceite de oliva" - 100 gr de queso parmesano" - 5 gr de romero" '},
    {producto: 'BEGEL POCHADO', ingrediente: '500 gr de harina" - 15 g de levadura" - Agua tibia" - 10 gr de sal" - 45 ml de aceite de oliva" - 100 gr de queso parmesano" - 5 gr de romero" '},
    {producto: 'POLISH', ingrediente: '500 gr de harina" - 15 g de levadura" - Agua tibia" - 10 gr de sal" - 45 ml de aceite de oliva" - 100 gr de queso parmesano" - 5 gr de romero" '},
    {producto: 'MASA', ingrediente: '500gr harina" - 125 gr agua" - 18 gr sal" - 5 levadura"'},
    {producto: 'PANATTNE', ingrediente: '90 gr pasa - 140 gr pasas alubias - 160 gr naranjas - 160 gr limón - 80 ml ron - 5 gr levadura - 250 gr leche - 5 gr sal - 250 gr harina - 750 gr harina - 1 barra de mantequilla - 200 gr harina - 15 gr sal - 200 ml leche - 320 gr mantequilla - 30 gr levadura - 200 gr yemas'},
    {producto: 'PAN DE HUEVO', ingrediente: '200 gr de huevo - 105 gr leche fría - 500 gr harina - 140 gr sal - 240 gr mantequilla'},
    {producto: 'MASA FEITE', ingrediente: '1kg harina - 15 gr sal - 100 gr mantequilla - 550 gr agua fría - 2 pza. huevo - 650 gr mantequilla Flex roja'},
    {producto: 'MASA DANES', ingrediente: '1 kg de harina - 12 gr sal - 15 gr levadura - 350 gr de huevo - 240 ml leche - 240 gr azúcar - 100 gr mantequilla - 500 gr margarina Flex azul - 2 pza. huevo'},
    {producto: 'CREMA PATELERA', ingrediente: '1 lt de leche -6 yemas - 250 de azúcar - 70 gr de maicena - Canela en raja'},
    {producto: 'GLASSE', ingrediente: 'Clara de huevo - Leche o agua - Azúcar glass'},
    {producto: 'TELERAS', ingrediente: '1 kg harina - 80 gr manteca vegetal - 20 gr sal - 20 gr levadura  - 90 gr azúcar - 20 gr mejorante'},
    {producto: 'BOLILLOS', ingrediente: '1 kg harina - 20 gr sal - 20 gr levadura - 20 gr mejorante - Agua'},
    {producto: 'MANTECADA - PANQUE', ingrediente: '5	huevos - 400 harina - 400 gr azúcar - 500 mantequilla - 500 ml leche - 40 gr polvo para hornear '},
    {producto: 'FOVACE - FOVEE ', ingrediente: '75 ml agua - 110 gr harina - 5 gr levadura fresca - 50 ml agua - 8 gr levadura fresca - 700 gr harina - 18 gr sal - 50 ml aceite - 10 sal de grano'},
    {producto: 'YOYOS O BESOS', ingrediente: '1kg de harina” - 660 gr margarina” - 440 gr azúcar” - 150 gr huevo” - 1 pza yema” - 160 ml leche” 20 gr polvo para hornear” -140 gr manteqilla” - 1 kg azúcar refinada”'},
    {producto: 'CREMA DE COCO', ingrediente: '160 gr de leche polvo”2 lt de agua” 350 gr de azúcar”250 gr fécula”150 gr de coco rallado”'},
    {producto: 'PAY DE QUESO', ingrediente: 'Pote y medio de huevo” - 200 gr de queso” - 2 latas de nestlé” - Limón”1 kg de azúcar” - 1 kg de margarina” - 10 pz de huevo” - 2 kg harina”100 gr azúcar glass” - 1 pz de huevo” - 200 gr de harina” - 100 gr de harina”'},
    {producto: 'YOYOS', ingrediente: '500 gr azúcar”250 gr margarina” - 200 gr manteca vegetal” - 7 pza huevo” -  ½ de leche liquida” - 75 gr de masa de concha” - 75 gr royal” - Canela al gusto” '},
    {producto: 'PAN DE ELOTE', ingrediente: '500 gr masa” - 10 pza de huevo” - 750 gr azúcar” - Batir por 20 minutos” - 750 gr de harina”-  75 gr de royal” - 300 gr de aceite” - 100 ml de leche liquida” - 300 gr de agua” '},
    {producto: 'LUPITAS', ingrediente: '1.500 gr de azúcar” - 400 gr de huevo”- 400 gr leche” - 500 gr de manteca” - 3 kg de harina” - 80 gr de royal” - Color amarillo”'},
    {producto: 'DONAS', ingrediente: '1 kg de harina” - 150 gr de mantequilla” - 15 gr da sal” - 25 gr de levadura instantánea” Leche l/n” - 200 gr de huevo” - 15 ml vainilla “- 175 gr azúcar" '},
    {producto: 'BIZCOCHO DE SAGU', ingrediente: '1 kg de azúcar” - 1 lt de agua” - 1.750 de manteca” -2 kg de harina” - 150 ge royal” - 3 fecula” - Vainilla”'},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},
    {producto: '', ingrediente: ''},



]